// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr0nljisXRCVcDbJIU2ajLOFe8WTNEEx4',
    appId: '1:877555554177:web:fcb15eee2dcc2dd1c7fa80',
    messagingSenderId: '877555554177',
    projectId: 'internship-1f7a9',
    authDomain: 'internship-1f7a9.firebaseapp.com',
    storageBucket: 'internship-1f7a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlz5L8ifinbSJ-68FpwLyogkEqxjcT4lk',
    appId: '1:877555554177:android:fe20aad71645bc70c7fa80',
    messagingSenderId: '877555554177',
    projectId: 'internship-1f7a9',
    storageBucket: 'internship-1f7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddc0-xvYe9VkBMUcm83plPD8EH2Kgfvo',
    appId: '1:877555554177:ios:cb1d97a240cec843c7fa80',
    messagingSenderId: '877555554177',
    projectId: 'internship-1f7a9',
    storageBucket: 'internship-1f7a9.appspot.com',
    iosClientId: '877555554177-lp2nvbvh5pf94mtcbjgh1tbgkenl9pdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddc0-xvYe9VkBMUcm83plPD8EH2Kgfvo',
    appId: '1:877555554177:ios:cb1d97a240cec843c7fa80',
    messagingSenderId: '877555554177',
    projectId: 'internship-1f7a9',
    storageBucket: 'internship-1f7a9.appspot.com',
    iosClientId: '877555554177-lp2nvbvh5pf94mtcbjgh1tbgkenl9pdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticket',
  );
}
